-- AUTO-GENERATED by scripts/gen-addon-encounter-names.ts — do not edit by hand.
-- encounterID -> boss name (fallback display; imported plans carry their own names).
-- Stored on the addon namespace `ns` (not _G) to avoid global taint surface.
local _, ns = ...
ns.EncounterNames = {
  [3379] = "Nymrissa Wavecaller",
  [3420] = "Sszorak",
  [3421] = "The Twin Fangs",
  [3429] = "The Coiled Altar",
  [3445] = "Entombed Sentinels",
  [3455] = "Vashnik the Malignant",
  [3470] = "Nek'zali the Soulcoiler",
  [3492] = "Ula'tek",
  [3497] = "The Lost Explorers",
  [12813] = "Lithiel Cinderfury",
  [12825] = "Nalorakk",
  [12859] = "Ziekett",
  [12923] = "Charonus",
  [12993] = "Zul'jan",
  [61762] = "King Dazar",
  [61877] = "Avatar of Sethraliss",
  [112521] = "Kyrakka and Erkhart Stormvein",
}

-- Content groups for the addon navigation (category → group → boss).
-- Mythic+ : one group per dungeon, bosses = all its bosses (id only when resolved).
-- Raid    : one group per raid instance, bosses = all its bosses (id only when resolved).
ns.Content = {
  {
    key = "mythicplus", label = "Mythic+",
    groups = {
      { name="Altar of Fangs", kr="송곳니의 제단", bosses = {
        { name="Rav'i", kr="라비" },
        { name="The Writhing Coil", kr="격동하는 똬리" },
        { id=12993, name="Zul'jan", kr="줄잔" },
      } },
      { name="Murder Row", kr="죽음의 골목", bosses = {
        { name="Kystia Manaheart", kr="키스티아 마나하트" },
        { name="Zaen Bladesorrow", kr="자엔 블레이드소로우" },
        { name="Xathuux the Annihilator", kr="파멸자 자투스" },
        { id=12813, name="Lithiel Cinderfury", kr="리시엘 신더퓨리" },
      } },
      { name="Den of Nalorakk", kr="날로라크의 소굴", bosses = {
        { name="The Hoardmonger", kr="비축광" },
        { name="Sentinel of Winter", kr="겨울의 파수꾼" },
        { id=12825, name="Nalorakk", kr="날로라크" },
      } },
      { name="The Blinding Vale", kr="눈부신 골짜기", bosses = {
        { name="Lightblossom Trinity", kr="빛송이 삼위일체" },
        { name="Ikuzz the Light Hunter", kr="빛 사냥꾼 이쿠즈" },
        { name="Lightwarden Ruia", kr="빛의 감시자 루이아" },
        { id=12859, name="Ziekett", kr="지케트" },
      } },
      { name="Voidscar Arena", kr="공허흉터 투기장", bosses = {
        { name="Taz'Rah", kr="타즈라" },
        { name="Atroxus", kr="아트로서스" },
        { id=12923, name="Charonus", kr="차로누스" },
      } },
      { name="Temple of Sethraliss", kr="세스랄리스 사원", bosses = {
        { name="Adderis and Aspix", kr="애더리스와 아스픽스" },
        { name="Merektha", kr="메레크타" },
        { name="Galvazzt", kr="갈바즈트" },
        { id=61877, name="Avatar of Sethraliss", kr="세스랄리스의 화신" },
      } },
      { name="King's Rest", kr="왕들의 안식처", bosses = {
        { name="The Golden Serpent", kr="황금 날뱀" },
        { name="Mchimba the Embalmer", kr="장의사 음침바" },
        { name="The Council of Tribes", kr="부족 의회" },
        { id=61762, name="King Dazar", kr="초대 왕 다자르" },
      } },
      { name="Ruby Life Pools", kr="루비 생명의 웅덩이", bosses = {
        { name="Melidrussa Chillworn", kr="멜리드루사 칠원" },
        { name="Kokia Blazehoof", kr="코키아 블레이즈후프" },
        { id=112521, name="Kyrakka and Erkhart Stormvein", kr="카이락카와 에크하트 스톰베인" },
      } },
    },
  },
  {
    key = "raid", label = "Raid",
    groups = {
      { name="The Venomous Abyss", kr="맹독 심연", bosses = {
        { id=3470, name="Nek'zali the Soulcoiler", kr="영혼살무사 네크잘리" },
        { id=3445, name="Entombed Sentinels", kr="매장된 파수꾼" },
        { id=3455, name="Vashnik the Malignant", kr="악성의 바쉬니크" },
        { id=3497, name="The Lost Explorers", kr="길 잃은 탐험가" },
        { id=3420, name="Sszorak", kr="스조라크" },
        { id=3421, name="The Twin Fangs", kr="쌍둥이 송곳니" },
        { id=3429, name="The Coiled Altar", kr="똬리의 제단" },
        { id=3492, name="Ula'tek", kr="울라텍" },
        { id=3379, name="Nymrissa Wavecaller", kr="님리사 웨이브콜러" },
      } },
    },
  },
}
